black:
  max:
  - 115
  - 135
  - 135
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 255
  - 111
  min:
  - 37
  - 84
  - 35
green:
  max:
  - 200
  - 104
  - 235
  min:
  - 0
  - 0
  - 0
purple:
  max:
  - 255
  - 255
  - 114
  min:
  - 0
  - 145
  - 36
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 31
  - 158
  - 130
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
